[[redirects]]
  from = "http://mrfz.xyz/*"
  to = "https://mrfz.xyz"
  status = 301
  force = false

[[redirects]]
  from = "https://arkn.netlify.com"
  to = "https://mrfz.xyz"
  status = 301
  force = false
